-- The instance base currency, and the FX snapshot on every expense (#25).
--
-- Generated by drizzle-kit, with one hand-made adjustment: each of the four
-- added NOT NULL columns is created WITH a default, filled, and then has the
-- default DROPPED — so the column ends in exactly the shape the generator
-- asked for (NOT NULL, no default, matching `meta/0004_snapshot.json`) while
-- the statement also survives a table that already has rows.
--
-- Why the adjustment: `ADD COLUMN … NOT NULL` with no default aborts on a
-- non-empty table, and this file runs as the Kitchen `migrate` task, where a
-- failed task strands production on the previous release. The owner's standing
-- instruction is that there is no data to be careful about ("we have no data
-- except the initial setup"), and that where a row does exist a rate of 1.0 is
-- correct — the feature never worked, so nothing was ever meaningfully mixed.
-- `amount_base_cents = amount_cents` at `fx_rate = 1` records exactly that.
--
-- Why the defaults do not survive the migration: a default on
-- `events_expense.base_currency`/`fx_rate` would let a future insert that sets
-- `amount_base_cents` and forgets the other two stamp CHF-at-1 on a EUR
-- instance in silence — and the guard in `server/domain/instance-settings.ts`
-- would then freeze the instance base there. Without them such an insert
-- aborts, which is the failure anybody would rather have.
--
-- drizzle's migrator wraps the whole pending set in one transaction, so this
-- file cannot half-apply.
CREATE TABLE "events_instance_setting" (
	"id" text PRIMARY KEY NOT NULL,
	"base_currency" text DEFAULT 'CHF' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "base_currency" text DEFAULT 'CHF' NOT NULL;--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "fx_rate" numeric(20, 10) DEFAULT '1' NOT NULL;--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "amount_base_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "events_expense" SET "amount_base_cents" = "amount_cents";--> statement-breakpoint
ALTER TABLE "events_expense" ALTER COLUMN "base_currency" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "events_expense" ALTER COLUMN "fx_rate" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "events_expense" ALTER COLUMN "amount_base_cents" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "events_expense_share" ADD COLUMN "amount_base_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "events_expense_share" SET "amount_base_cents" = "amount_cents";--> statement-breakpoint
ALTER TABLE "events_expense_share" ALTER COLUMN "amount_base_cents" DROP DEFAULT;
