-- The instance base currency, and the FX snapshot on every expense (#25).
--
-- Generated by drizzle-kit, with one hand-made adjustment: the two
-- `amount_base_cents` columns are added WITH a default, filled from the
-- as-spent amount, and then have the default dropped — so the final column
-- shape is exactly the generated one (NOT NULL, no default) while the
-- statement also survives a table that already has rows.
--
-- `ADD COLUMN … integer NOT NULL` as generated aborts on a non-empty table,
-- and this migration runs as a Kitchen deploy task: a failed task strands
-- production on the previous release. The owner's standing instruction is that
-- there is no data to be careful about ("we have no data except the initial
-- setup"), and that where a row does exist a rate of 1.0 is correct — the
-- feature never worked, so nothing was ever meaningfully mixed. That is
-- precisely what `amount_base_cents = amount_cents` records.
CREATE TABLE "events_instance_setting" (
	"id" text PRIMARY KEY NOT NULL,
	"base_currency" text DEFAULT 'CHF' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "base_currency" text DEFAULT 'CHF' NOT NULL;--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "fx_rate" numeric(20, 10) DEFAULT '1' NOT NULL;--> statement-breakpoint
ALTER TABLE "events_expense" ADD COLUMN "amount_base_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "events_expense" SET "amount_base_cents" = "amount_cents";--> statement-breakpoint
ALTER TABLE "events_expense" ALTER COLUMN "amount_base_cents" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "events_expense_share" ADD COLUMN "amount_base_cents" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "events_expense_share" SET "amount_base_cents" = "amount_cents";--> statement-breakpoint
ALTER TABLE "events_expense_share" ALTER COLUMN "amount_base_cents" DROP DEFAULT;
